import { Inter } from 'next/font/google'
import './globals.css'
import BottomNavigation from './components/BottomNavigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Drawing App',
  description: 'Generated by olanike',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <BottomNavigation/>
        </body>
    </html>
  )
}
