import { Inter } from "next/font/google";
import "./globals.css";
import { authOptions } from "../../pages/api/auth/[...nextauth]";
import { getServerSession } from "next-auth";
import SessionProvider from "./components/SessionProvider";
import Login from "./components/Login";
import Home from "./page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Drawing App",
  description: "Generated by olanike",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          {!session ? <Login /> : children}
        </SessionProvider>
      </body>
    </html>
  );
}
